name: church_presenter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  http: ^1.2.2
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.1
  wakelock_plus: ^1.2.8
  sqflite: ^2.3.3+2
  path: ^1.9.0
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/presenter/web/index.html
  - assets/bible/
  - assets/bible/Books.json
  - assets/bible/Genesis.json
  - assets/bible/Exodus.json
  - assets/bible/Leviticus.json
  - assets/bible/Numbers.json
  - assets/bible/Deuteronomy.json
  - assets/bible/Joshua.json
  - assets/bible/Judges.json
  - assets/bible/Ruth.json
  - assets/bible/1 Samuel.json
  - assets/bible/2 Samuel.json
  - assets/bible/1 Kings.json
  - assets/bible/2 Kings.json
  - assets/bible/1 Chronicles.json
  - assets/bible/2 Chronicles.json
  - assets/bible/Ezra.json
  - assets/bible/Nehemiah.json
  - assets/bible/Esther.json
  - assets/bible/Job.json
  - assets/bible/Psalms.json
  - assets/bible/Proverbs.json
  - assets/bible/Ecclesiastes.json
  - assets/bible/Song of Songs.json
  - assets/bible/Isaiah.json
  - assets/bible/Jeremiah.json
  - assets/bible/Lamentations.json
  - assets/bible/Ezekiel.json
  - assets/bible/Daniel.json
  - assets/bible/Hosea.json
  - assets/bible/Joel.json
  - assets/bible/Amos.json
  - assets/bible/Obadiah.json
  - assets/bible/Jonah.json
  - assets/bible/Micah.json
  - assets/bible/Nahum.json
  - assets/bible/Habakkuk.json
  - assets/bible/Zephaniah.json
  - assets/bible/Haggai.json
  - assets/bible/Zechariah.json
  - assets/bible/Malachi.json
  - assets/bible/Matthew.json
  - assets/bible/Mark.json
  - assets/bible/Luke.json
  - assets/bible/John.json
  - assets/bible/Acts.json
  - assets/bible/Romans.json
  - assets/bible/1 Corinthians.json
  - assets/bible/2 Corinthians.json
  - assets/bible/Galatians.json
  - assets/bible/Ephesians.json
  - assets/bible/Philippians.json
  - assets/bible/Colossians.json
  - assets/bible/1 Thessalonians.json
  - assets/bible/2 Thessalonians.json
  - assets/bible/1 Timothy.json
  - assets/bible/2 Timothy.json
  - assets/bible/Titus.json
  - assets/bible/Philemon.json
  - assets/bible/Hebrews.json
  - assets/bible/James.json
  - assets/bible/1 Peter.json
  - assets/bible/2 Peter.json
  - assets/bible/1 John.json
  - assets/bible/2 John.json
  - assets/bible/3 John.json
  - assets/bible/Jude.json
  - assets/bible/Revelation.json
