name: church_presenter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  http: ^1.2.2
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.1
  wakelock_plus: ^1.2.8
  sqflite: ^2.3.3+2
  path: ^1.9.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/presenter/web/index.html
  - assets/bible/
